version: "3.8"

services:
  concurrent-python:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/app
    working_dir: /app
    tty: true
    entrypoint: /bin/bash
